### ISSUE TITLE
[Feature] Support dry run in rollout-image

### ISSUE THREAD

**Issue by anoriqq** [CircleCI-Public/gcp-gke-orb#23]
### Orb version

0.2.0

### What happened

I want to use dry-run for rollout-image command.

### Expected behavior

I've patched my inline orb to add dry-run parameter.

```yaml
commands:
  rollout-image:
    parameters:
      dry-run:
        default: none
        description: |
          Must be "none", "server", or "client". If client strategy, only print the object that would be sent, without sending it. If server strategy, submit server-side request without persisting the resource.
        type: string
    steps:
      - gke/update-kubeconfig-with-credentials:
          cluster: <<parameters.cluster>>
      - run:
          command: >
            DRY_RUN="<< parameters.dry-run >>"
            if [ -n "<<parameters.namespace>>" ]; then
              set -- "$@" --namespace="<<parameters.namespace>>"
            fi
            set -- "$@" "--dry-run=${DRY_RUN}"
            kubectl set image deployment <<parameters.deployment>>
            <<parameters.container>>=<<parameters.image>>:<<parameters.tag>> "$@"
```
