### ISSUE TITLE
Docs: Define more explicit use-case example

### ISSUE THREAD

**Issue by Jaryt** [CircleCI-Public/gcp-gke-orb#44]
## Describe Request:

Documentation on gcp-gke orb usage is not explicit. As presented in #25, users might expect to be able to have clusters persist between pipeline runs. This is to prevent infrastructure as code managed by CI config. We want to enforce that all infrastructure created in pipeline is ephemeral and **MUST** be removed by the end of the same pipeline. 

## Examples:

```
orbs:
  gke: circleci/gcp-gke@x.y.z
version: 2.1
workflows:
  main:
    jobs:
      - gke/create-cluster:
          cluster: gcp-testing
      - run-cluster-command
      - gke/delete-cluster:
          cluster: gcp-testing
```

## Supporting Documentation Links:

https://cloud.google.com/sdk/gcloud/reference/container/clusters/create
