### ISSUE TITLE
GOOGLE_COMPUTE_REGION is ignored on "update-kubeconfig-with-credentials"

### ISSUE THREAD

**Issue by sttr-asano** [CircleCI-Public/gcp-gke-orb#47]
## What happened:
Environment variable `$GOOGLE_COMPUTE_REGION` is ignored, and command `update-kubeconfig-with-credentials` fails for asia-northeast1 cluster.

e.g.
```yaml
jobs:
  gke-test:
    environment:
      GOOGLE_COMPUTE_REGION: asia-northeast1
      GOOGLE_PROJECT_ID: my_project_name
    machine:
      image: ubuntu-2004:202111-01
    working_directory: ~/repo
    steps:
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: my-cluster-name
          install-kubectl: true
          perform-login: true
```

## Expected behavior:
kubeconfig update success

## Additional Information:
It succeeds by specifying region in cluster name 
`cluster: "my-cluster-name --region=asia-northeast1"`

**Comment by sttr-asano** [comment]
I found `get-credentials` succeeds with newer version of gcloud.
so I want newer gcloud version bundled...

```
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: my-cluster-name
          install-kubectl: true
          perform-login: true
      # It fails
      - run:
           name: update kubeconfig
          command: |
            gcloud container clusters get-credentials my-cluster-name
          when: always
      # Install newer version of gcloud
      - gcp-cli/install:
          version: 371.0.0
      # It succeeds
      - run:
          name: update kubeconfig
          command: |
            gcloud container clusters get-credentials my-cluster-name
          when: always
```
