### ISSUE TITLE
Unable to reference publish-and-rollout-image from custom job

### ISSUE THREAD

**Issue by Stianhn** [CircleCI-Public/gcp-gke-orb#49]
This config gives me this error: Cannot find a definition for command named gke/publish-and-rollout-image

```
version: 2.1
orbs:
  gke: circleci/gcp-gke@1.4.0
jobs:
  publish:
    executor: gke/default
    steps:
      - gke/publish-and-rollout-image

workflows:
  main:
    jobs:
      - publish
```

But if I change the step to one of the other jobs, like create-cluster, it seems to find the job definition. Is this a bug or am I missing something?
