### ISSUE TITLE
[FEATURE] Support tag in deployment

### ISSUE THREAD

**Issue by hawksight** [CircleCI-Public/gcp-gke-orb#5]
in the `rollout_image` command, there is no option to add an image tag [here](https://github.com/CircleCI-Public/gcp-gke-orb/blob/master/orb.yml#L38)

```
    steps:
      - run: |
          gcloud container clusters get-credentials <<parameters.cluster>>
          kubectl set image deployment <<parameters.deployment>> <<parameters.container>>=<<parameters.image>>
```

I've patched my local command to add the parameter:
```
      image_tag:
        description: The images tag version
        type: string
        default: $CIRCLE_SHA1
    steps:
      - run: |
          gcloud container clusters get-credentials <<parameters.cluster>>
          kubectl set image deployment <<parameters.deployment>> <<parameters.container>>=<<parameters.image>>:<<parameters.image_tag>> --record
```

I think this needs added as I hit an error when there was not tag specified.
I think it will also keep consistency withe the [gcp-gcr](https://github.com/CircleCI-Public/gcp-gcr-orb) orb where `tag` is a [parameter](https://github.com/CircleCI-Public/gcp-gcr-orb/blob/master/src/jobs/build-and-push-image.yml#L31-L34)
