### ISSUE TITLE
Switch to using gke-gcloud-auth-plugin to prevent build failures when the next version of k8s releases.

### ISSUE THREAD

**Issue by novedevo** [CircleCI-Public/gcp-gke-orb#61]
## Describe Request:
Switch to using gke-gcloud-auth-plugin to prevent build failures when the next version of k8s releases.
## Examples:
Running the `update-kubeconfig-with-credentials` command results in the following bright red warning:

`CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable. Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke`

## Supporting Documentation Links:
https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

**Comment by legopin** [comment]
So what is the solution now. 

Today our CI begin to have full error instead of warning.

We were actually using the 1.3.0 version of circleci/gcp-gke@1.3.0
I was expecting that since our GKE server is still at 1.22 that the change wouldn't affect us, since the pinned version of the orb would use the older kubectl command

What is the advised fix? Use the newer version of circleci/gcp-gke@1.4.0?

```
error: The gcp auth plugin has been removed.
Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details
```

**Comment by krainet** [comment]
Same here guys

**Comment by ReccoD** [comment]
Same here

**Comment by philip-newzoo** [comment]
> > Any update?
> 
> Figured out the proper way to solve this, and working on getting the implementation in tonight. Should have a release ASAP.

Could we get a fix for this ASAP? We're running into the issue now and it's impacting our ability to deploy our releases.

**Comment by pokEarl** [comment]
> > Any update?
> 
> Figured out the proper way to solve this, and working on getting the implementation in tonight. Should have a release ASAP.

@Jaryt Hej we are also having some issues with this, if there is an easy way to fix this it would be great 🤪

**Comment by pokEarl** [comment]
Ok think I've made it work for our deploys at least 🎊  What I did: 

1) Updated Gcp-cli version to 3.0.0 (changed /initialize to /setup and change credential keys to use _ instead of -)

2) Added a command to install it directly 
      - gcp-cli/install
      - run:
          name: Installs new Gcloud Auth Plugin 
          command: gcloud components install gke-gcloud-auth-plugin

3) Added the environment variable USE_GKE_GCLOUD_AUTH_PLUGIN=True

**Comment by EricRibeiro** [comment]
Hey folks

Thanks for sharing workarounds! Please stick to @pokEarl's suggestion while I work on a fix.

**Comment by willnevillain** [comment]
We ran into this too and it blocked our deploys; if it's helpful to others, here's our workaround in the meantime:

- add installation of a version tagged `kubectl` in an `install_dependencies` script we run at the beginning of our deploy job. Tagged to `1.25.4` before the gcp auth plugin was removed.
- remove the `gke/install` step (not required since `gcloud` was being installed earlier via a `gcp-gcr/gcr-auth` orb step)

Our script looks like this:
```bash
#!/bin/bash

set -e

# Create a user bin
_bin="$HOME/bin"
mkdir -v -p "$_bin"

# Install kubectl
kubectl_version=v1.25.4

wget https://dl.k8s.io/release/$kubectl_version/bin/linux/amd64/kubectl
chmod +x kubectl
mv kubectl $_bin
```

**Comment by neilpoulin** [comment]
the [suggested fix](https://github.com/CircleCI-Public/gcp-gke-orb/issues/61#issuecomment-1344517115) doesn't work for me. I get the error shown below. 

![image](https://user-images.githubusercontent.com/802410/206798775-19da59f2-b491-4c2d-8c3d-94f2f1e1e1b2.png)

My job looks like this: 

```yml
orbs:
  node: circleci/node@5.0.3
  slack: circleci/slack@4.4.4
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gcp-cli: circleci/gcp-cli@3.0.0

# Other configs/commands not shown

  deploy-to-dev:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - gcp-gke/install
      - gcp-cli/install # NEW JOB HERE
      - run: # NEW JOB HERE
          name: Installs new Gcloud Auth Plugin
          command: gcloud components install gke-gcloud-auth-plugin
      - run:
          name: 'Login to Google Cloud'
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - gcp-gke/rollout-image:
          cluster: pluto-dev
          deployment: dev-pluto-web
          container: pluto-web
          image: gcr.io/pluto-staging-299000/pluto-web
          tag: $CIRCLE_SHA1
      - run: |
          curl -sL https://sentry.io/get-cli/ | bash
          export SENTRY_RELEASE=$CIRCLE_SHA1
          sentry-cli releases deploys $SENTRY_RELEASE new -e dev-stage
```

**Comment by EricRibeiro** [comment]
@neilpoulin, can you share the output of `gcp-cli/install`? The error message you received says that `path.bash.inc` does not exist. This file should've been downloaded from the CLI's install job.

Also, remove `gcp-gke/install`. You don't need it since you are installing the CLI via the `gcp-cli` orb.

**Comment by neilpoulin** [comment]
@EricRibeiro Thank you for the reply. I updated my job as you suggested, and now have a different error. 

```
# Roll out image
/bin/bash: line 5: kubectl: command not found

Exited with code exit status 127
```

Any more help on this would be greatly appreciated, i'm trying get some critical changes out to production and am totally blocked. 

Below is as much output as i could grab

## entire Job overview
![image](https://user-images.githubusercontent.com/802410/206804745-249f531b-1c22-47dd-9f63-1b4507b5b2b9.png)

## Install latest gcloud CLI version full output 
![image](https://user-images.githubusercontent.com/802410/206804837-005b7f60-e65a-42a3-9dcd-0e8039766e56.png)

**Comment by EricRibeiro** [comment]
Thanks! It looks like all you need is `kubectl` now. You should be able to install it using the Kubernetes orb:

```yaml
orbs:
  ...
  k8s: circleci/kubernetes@1.3.1

# Other configs/commands not shown

  deploy-to-dev:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - gcp-cli/install:
           components: gke-gcloud-auth-plugin
      - run:
          name: 'Login to Google Cloud'
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - k8s/install-kubectl
     ...
```

FYI, you can replace your entire `Login to Google Cloud` step with the CLI's initialize command; it takes care of the authentication for you.

**Comment by neilpoulin** [comment]
@EricRibeiro I got it working, but not with your latest suggestion. For completeness, here is the error thrown using your approach of using `k8s/intstall-kubectl` 

## Failed approach with k8s/install-kubectl

```yml
# Updated deploy job - errors out 
orbs:
  node: circleci/node@5.0.3
  slack: circleci/slack@4.4.4
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gcp-cli: circleci/gcp-cli@3.0.0
  k8s: circleci/kubernetes@1.3.1

# other commands/jobs not shown

  deploy-to-dev:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - gcp-cli/install:
          components: gke-gcloud-auth-plugin      
      - run:
          name: 'Login to Google Cloud'
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - k8s/install-kubectl
      - gcp-gke/rollout-image:
          cluster: pluto-dev
          deployment: dev-pluto-web
          container: pluto-web
          image: gcr.io/pluto-staging-299000/pluto-web
          tag: $CIRCLE_SHA1
      - run: |
          curl -sL https://sentry.io/get-cli/ | bash
          export SENTRY_RELEASE=$CIRCLE_SHA1
          sentry-cli releases deploys $SENTRY_RELEASE new -e dev-stage

```

![image](https://user-images.githubusercontent.com/802410/206810433-4f8aa235-2dc9-4799-bc57-fc9a0b457b05.png)


## Working config, install kubectl manually

```yml
  deploy-to-dev:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - gcp-cli/install:
          components: gke-gcloud-auth-plugin      
      - run:
          name: 'Login to Google Cloud'
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: 'Install kubectl'
          command: |
            gcloud components install kubectl
      - gcp-gke/rollout-image:
          cluster: pluto-dev
          deployment: dev-pluto-web
          container: pluto-web
          image: gcr.io/pluto-staging-299000/pluto-web
          tag: $CIRCLE_SHA1
```
